"""add missing cols

Revision ID: 65452a2dcec8
Revises: 9895e9472911
Create Date: 2026-06-02 23:47:31.645002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65452a2dcec8'
down_revision: Union[str, Sequence[str], None] = '9895e9472911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('documentchunk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentchunk', schema=None) as batch_op:
        batch_op.drop_column('page_number')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('embedding_model_version')

    # ### end Alembic commands ###
